name: Deploy Lovable Frontend to OCI Prod

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or specify a precise version like '1.x.x'

      - name: Install Dependencies
        run: |
          # The checkout action already places repo contents at the workspace root
          # So, 'beracode-site-genesis' is your current working directory here.
          bun install # Install dependencies using Bun

      - name: Build Frontend
        run: |
          # Again, 'beracode-site-genesis' is your current working directory.
          bun run build # Run the build command using Bun
        # This will create the 'dist' folder directly in the workspace root now

      - name: Clean and Prepare Target Directory on Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/html/beracode
            sudo mkdir -p /var/www/html/beracode
            sudo chown -R ${{ secrets.VPS_USER }}:www-data /var/www/html/beracode
            sudo chmod -R 755 /var/www/html/beracode

      - name: Synchronize Build Files To Server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # The SOURCE path is now just "dist/" because it's directly in the workspace root
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          TARGET: "/var/www/html/beracode"
          EXCLUDE: |
            .git/
            node_modules/
            dist/

      - name: Reload Nginx on Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl reload nginx