# .github/workflows/deploy.yml

name: Deploy Lovable Frontend to OCI Prod

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # This is the corrected syntax for clearing Bun's cache
      - name: Clear Bun Cache
        run: bun cache clean

      - name: Install Dependencies
        run: bun install

      - name: Build Frontend
        run: bun run build

      # Prepares the target directory on the server for the deploy
      - name: Prepare Target Directory for Rsync
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: opc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/html/beracode
            sudo chown -R opc:opc /var/www/html/beracode
            sudo chmod -R 755 /var/www/html/beracode

      # Synchronizes build files to the server
      - name: Synchronize Build Files To Server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: opc
          TARGET: "/var/www/html/beracode/"
          EXCLUDE: ".git/"
          ARGS: "-avz --delete"

      # Sets final permissions for Nginx and reloads the web server
      - name: Set Final Nginx Permissions and Reload Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: opc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            NGINX_USER=$(grep -Po '^\s*user\s+\K[^;]+' /etc/nginx/nginx.conf | head -1 || echo 'nginx')
            
            sudo chown -R $NGINX_USER:$NGINX_USER /var/www/html/beracode
            
            sudo find /var/www/html/beracode -type f -exec chmod 644 {} \;
            
            sudo find /var/www/html/beracode -type d -exec chmod 755 {} \;
            
            sudo nginx -t
            
            if [ $? -eq 0 ]; then
                echo "Nginx configuration test successful. Reloading Nginx..."
                sudo systemctl reload nginx
            else
                echo "Nginx configuration test failed. Check logs for errors."
                exit 1
            fi
