name: Deploy Lovable Frontend to OCI Prod

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or specify a precise version like '1.x.x'

      - name: Install Dependencies
        run: |
          bun install

      - name: Build Frontend
        run: |
          bun run build

      - name: Clean and Prepare Target Directory on Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: opc # Changed to opc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/html/beracode
            sudo mkdir -p /var/www/html/beracode
            # Changed group to nginx, common for Nginx on Oracle Linux/RHEL
            sudo chown -R opc:nginx /var/www/html/beracode
            sudo chmod -R 755 /var/www/html/beracode

      - name: Synchronize Build Files To Server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: opc # Changed to opc
          TARGET: "/var/www/html/beracode"
          EXCLUDE: ".git/"

      - name: Reload Nginx on Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: opc # Changed to opc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl reload nginx
